site_name: Hack-Wiki-Commands
nav:
    - Home: index.md
    - About: about.md
    - Persistence:
        - 'Schtasks': 'Persistence/schtask.md'
    - Wifi:
        - 'Wlan Extract Pass': 'Wifi/Wlan_Extract_Info/wlanExtractIndo.md'
        - 'Config Wifi Linux': 'Wifi/WlanConfig/configWifi.md'
        - 'Weak Routes': 'Wifi/Airckark/wifi_hack_tecnics.md'
    - Aircrack-ng:
        - 'Karma': 'Wifi/Airckark/karmaHAKK.md'
        - 'Aircrak Commands': 'Wifi/Airckark/aircrack_comands.md'
        - 'Evil Twing': 'Wifi/Airckark/Evil_tiwn.md'
    - Android:
        - 'Pentest': 'Android/android-pentest.md'
        - 'Analysis Methodology': 'Android/android-MetodologiaAnalisis.md'
        - 'Inspect Certificate': 'Android/android-Certificates.md'
        - 'ADB Commands': 'Android/androidADB.md'
        - 'Android Debug Enviroment': 'Android/android_Debug_enviroment.md'
        - 'Decompile APK': 'Android/android_Decompile.md'
        - 'Android Monitoring': 'Android/android_monitor.md'
        - 'Cordoba Phonegapp': 'Android/cordoba-securityAspects.md'
        - 'Manage APKs': 'Android/android-APK.md'
        - 'SDK': 'Android/android-SDK.md'
    - Ethical Hacking:
        - 'Linux Commands': 'CPHE/00-ComandosLINUX.md'
        - 'Information Gathering': 'CPHE/01-RecoleccionInformación.md'
        - 'Nmap': 'CPHE/02-Nmap.md'
        - 'Acunetix': 'CPHE/03-Acunetix.md'
        - 'OWASP ZAP': 'CPHE/03-OWASP_ZAP.md'
        - 'Nessus': 'CPHE/04-Nessus.md'
        - 'Exploit Automation': 'CPHE/05-Exploiting-Automatizado.md'
        - 'Exploit Client Site': 'CPHE/05-Exploiting-ClientSite.md'
        - 'Crack Passwords': 'CPHE/05-Exploiting-CrackPasswords.md'
        - 'Privilege Escalation': 'CPHE/05-Exploiting-ExcaladaPriv.md'
        - 'Manual Exploiting': 'CPHE/05-Exploiting-Manual.md'
        - 'Pivoting': 'CPHE/05-Exploiting-Pivoting.md'
        - 'Post Explotation': 'CPHE/05-Exploiting-PostExplotacion.md'
        - 'Network Exploiting': 'CPHE/05-Exploiting-Red.md'
        - 'Password': 'CPHE/06-Passwords.md'
        - 'Wifi': 'CPHE/07-Wifi.md'
        - 'Malware': 'CPHE/08-Malware.md'
        - 'Forensic': 'CPHE/09-Forense.md'
        - 'Web': 'CPHE/10-Web.md'
theme: readthedocs
